import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, extname } from 'path';

// Recursively get all .ts and .tsx files, excluding node_modules and .next
function getFiles(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    if (entry === 'node_modules' || entry === '.next' || entry === 'fix-accents.mjs') continue;
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      getFiles(full, files);
    } else if (extname(full) === '.ts' || extname(full) === '.tsx') {
      files.push(full);
    }
  }
  return files;
}

// Ordered replacements (longer first to avoid partial matches)
// Each pair: [regex pattern, replacement]
// We use word boundaries to be safe
const replacements = [
  // Very long words first
  [/\baccelerationniste\b/g, 'accélérationniste'],
  [/\bdesindustrialisation\b/g, 'désindustrialisation'],
  [/\bmacroeconomique\b/g, 'macroéconomique'],
  [/\bmacroeconomiques\b/g, 'macroéconomiques'],
  [/\bMacroeconomie\b/g, 'Macroéconomie'],
  [/\bmacroeconomie\b/g, 'macroéconomie'],
  [/\bMicroeconomie\b/g, 'Microéconomie'],
  [/\bmicroeconomie\b/g, 'microéconomie'],
  [/\bsupplementaires\b/g, 'supplémentaires'],
  [/\bsupplementaire\b/g, 'supplémentaire'],
  [/\bintermediaire\b/g, 'intermédiaire'],
  [/\bIntermediaire\b/g, 'Intermédiaire'],
  [/\bintermediaires\b/g, 'intermédiaires'],
  [/\breglementation\b/g, 'réglementation'],
  [/\bReglementation\b/g, 'Réglementation'],
  [/\bliberalisation\b/g, 'libéralisation'],
  [/\bselectionnee\b/g, 'sélectionnée'],
  [/\bpredefinie\b/g, 'prédéfinie'],
  [/\bpredefinies\b/g, 'prédéfinies'],
  [/\bpreconfigure\b/g, 'préconfiguré'],
  [/\bsimultanement\b/g, 'simultanément'],
  [/\benergetique\b/g, 'énergétique'],
  [/\bgeographique\b/g, 'géographique'],
  [/\bpedagogique\b/g, 'pédagogique'],
  [/\bPedagogique\b/g, 'Pédagogique'],
  [/\begalitaire\b/g, 'égalitaire'],
  [/\binegalitaire\b/g, 'inégalitaire'],
  [/\binegalites\b/g, 'inégalités'],
  [/\bInegalites\b/g, 'Inégalités'],
  [/\binegalite\b/g, 'inégalité'],
  [/\bInegalite\b/g, 'Inégalité'],
  [/\bcompetitivite\b/g, 'compétitivité'],
  [/\bCompetitivite\b/g, 'Compétitivité'],
  [/\bpresentation\b/g, 'présentation'],
  [/\bdeplacement\b/g, 'déplacement'],
  [/\bgeneralise\b/g, 'généralisé'],
  [/\bgeneralisee\b/g, 'généralisée'],
  [/\bgeneration\b/g, 'génération'],
  [/\bnecessairement\b/g, 'nécessairement'],
  [/\bnecessaires\b/g, 'nécessaires'],
  [/\bnecessaire\b/g, 'nécessaire'],
  [/\bnecessite\b/g, 'nécessité'],
  [/\bdefaillances\b/g, 'défaillances'],
  [/\bdefaillance\b/g, 'défaillance'],
  [/\bdesinflation\b/g, 'désinflation'],
  [/\bDesinflation\b/g, 'Désinflation'],
  [/\bdesincitation\b/g, 'désincitation'],
  [/\beconomiques\b/g, 'économiques'],
  [/\beconomique\b/g, 'économique'],
  [/\bequilibres\b/g, 'équilibres'],
  [/\bequilibre\b/g, 'équilibre'],
  [/\bEquilibre\b/g, 'Équilibre'],
  [/\bevenements\b/g, 'événements'],
  [/\bevenement\b/g, 'événement'],
  [/\bphenomenes\b/g, 'phénomènes'],
  [/\bphenomene\b/g, 'phénomène'],
  [/\bhypotheses\b/g, 'hypothèses'],
  [/\bhypothese\b/g, 'hypothèse'],
  [/\bmonetaires\b/g, 'monétaires'],
  [/\bmonetaire\b/g, 'monétaire'],
  [/\bMonetaire\b/g, 'Monétaire'],
  [/\bmecanismes\b/g, 'mécanismes'],
  [/\bmecanisme\b/g, 'mécanisme'],
  [/\bMecanisme\b/g, 'Mécanisme'],
  [/\beconomies\b/g, 'économies'],
  [/\beconomie\b/g, 'économie'],
  [/\bEconomie\b/g, 'Économie'],
  [/\bpreferences\b/g, 'préférences'],
  [/\bpreference\b/g, 'préférence'],
  [/\bspecifiques\b/g, 'spécifiques'],
  [/\bspecifique\b/g, 'spécifique'],
  [/\bstrategies\b/g, 'stratégies'],
  [/\bstrategie\b/g, 'stratégie'],
  [/\btheorique\b/g, 'théorique'],
  [/\btheoriques\b/g, 'théoriques'],
  [/\btheoreme\b/g, 'théorème'],
  [/\bTheoreme\b/g, 'Théorème'],
  [/\btheories\b/g, 'théories'],
  [/\btheorie\b/g, 'théorie'],
  [/\befficacite\b/g, 'efficacité'],
  [/\bEfficacite\b/g, 'Efficacité'],
  [/\belasticites\b/g, 'élasticités'],
  [/\belasticite\b/g, 'élasticité'],
  [/\bElasticite\b/g, 'Élasticité'],
  [/\binelastiques\b/g, 'inélastiques'],
  [/\binelastique\b/g, 'inélastique'],
  [/\belastiques\b/g, 'élastiques'],
  [/\belastique\b/g, 'élastique'],
  [/\bstabilite\b/g, 'stabilité'],
  [/\bopportunite\b/g, 'opportunité'],
  [/\bprosperite\b/g, 'prospérité'],
  [/\bprospere\b/g, 'prospère'],
  [/\bseverite\b/g, 'sévérité'],
  [/\bdepenses\b/g, 'dépenses'],
  [/\bDepenses\b/g, 'Dépenses'],
  [/\bdepense\b/g, 'dépense'],
  [/\bDepense\b/g, 'Dépense'],
  [/\bsocietes\b/g, 'sociétés'],
  [/\bsociete\b/g, 'société'],
  [/\brealistes\b/g, 'réalistes'],
  [/\brealiste\b/g, 'réaliste'],
  [/\brealite\b/g, 'réalité'],
  [/\bsystemes\b/g, 'systèmes'],
  [/\bsysteme\b/g, 'système'],
  [/\bSysteme\b/g, 'Système'],
  [/\bmodeles\b/g, 'modèles'],
  [/\bmodele\b/g, 'modèle'],
  [/\bModele\b/g, 'Modèle'],
  [/\bperiodes\b/g, 'périodes'],
  [/\bperiode\b/g, 'période'],
  [/\binterets\b/g, 'intérêts'],
  [/\binteret\b/g, 'intérêt'],
  [/\bInterieur\b/g, 'Intérieur'],
  [/\binterieur\b/g, 'intérieur'],
  [/\binterieure\b/g, 'intérieure'],
  [/\betrangers\b/g, 'étrangers'],
  [/\betrangere\b/g, 'étrangère'],
  [/\betrangeres\b/g, 'étrangères'],
  [/\bepargne\b/g, 'épargne'],
  [/\bEpargne\b/g, 'Épargne'],
  [/\bechangees\b/g, 'échangées'],
  [/\bechangee\b/g, 'échangée'],
  [/\bechanges\b/g, 'échanges'],
  [/\bechange\b/g, 'échange'],
  [/\bpremieres\b/g, 'premières'],
  [/\bpremiere\b/g, 'première'],
  [/\bdeficits\b/g, 'déficits'],
  [/\bdeficit\b/g, 'déficit'],
  [/\bDeficit\b/g, 'Déficit'],
  [/\bdeficitaire\b/g, 'déficitaire'],
  [/\bdefinies\b/g, 'définies'],
  [/\bdefinie\b/g, 'définie'],
  [/\bdefini\b/g, 'défini'],
  [/\bdefinit\b/g, 'définit'],
  [/\bdeplacees\b/g, 'déplacées'],
  [/\bdeplacee\b/g, 'déplacée'],
  [/\bdeplace\b/g, 'déplace'],
  [/\bdepasser\b/g, 'dépasser'],
  [/\bdepasse\b/g, 'dépasse'],
  [/\betudiants\b/g, 'étudiants'],
  [/\betudiant\b/g, 'étudiant'],
  [/\bEtats-Unis\b/g, 'États-Unis'],
  [/\begalite\b/g, 'égalité'],
  [/\bEgalite\b/g, 'Égalité'],
  [/\bpetroliere\b/g, 'pétrolière'],
  [/\bpetrolier\b/g, 'pétrolier'],
  [/\bpetrole\b/g, 'pétrole'],
  [/\bheritages\b/g, 'héritages'],
  [/\bheritage\b/g, 'héritage'],
  [/\bgeneralement\b/g, 'généralement'],
  [/\bgenerale\b/g, 'générale'],
  [/\bgeneraux\b/g, 'généraux'],
  [/\bgeneral\b/g, 'général'],
  [/\breformes\b/g, 'réformes'],
  [/\breforme\b/g, 'réforme'],
  [/\breflete\b/g, 'reflète'],
  [/\breelles\b/g, 'réelles'],
  [/\breelle\b/g, 'réelle'],
  [/\breels\b/g, 'réels'],
  [/\breel\b/g, 'réel'],
  [/\bsalaries\b/g, 'salariés'],
  [/\bsalarie\b/g, 'salarié'],
  [/\bFiscalite\b/g, 'Fiscalité'],
  [/\bfiscalite\b/g, 'fiscalité'],
  [/\bProductivite\b/g, 'Productivité'],
  [/\bproductivites\b/g, 'productivités'],
  [/\bproductivite\b/g, 'productivité'],
  [/\bnegatifs\b/g, 'négatifs'],
  [/\bnegatif\b/g, 'négatif'],
  [/\bnegatives\b/g, 'négatives'],
  [/\bnegative\b/g, 'négative'],
  [/\bNegative\b/g, 'Négative'],
  [/\bnumeros\b/g, 'numéros'],
  [/\bnumero\b/g, 'numéro'],
  [/\belevees\b/g, 'élevées'],
  [/\belevee\b/g, 'élevée'],
  [/\beleves\b/g, 'élevés'],
  [/\beleve\b/g, 'élevé'],
  [/\bspecialisation\b/g, 'spécialisation'],
  [/\bSpecialisation\b/g, 'Spécialisation'],
  [/\bspecialisee\b/g, 'spécialisée'],
  [/\bspecialise\b/g, 'spécialisé'],
  [/\bspecialiser\b/g, 'spécialiser'],
  [/\bcreent\b/g, 'créent'],
  [/\bcreees\b/g, 'créées'],
  [/\bcreee\b/g, 'créée'],
  [/\bCreation\b/g, 'Création'],
  [/\bcreation\b/g, 'création'],
  [/\bcree\b/g, 'crée'],
  [/\bdeterminants\b/g, 'déterminants'],
  [/\bdeterminent\b/g, 'déterminent'],
  [/\bdetermine\b/g, 'détermine'],
  [/\bDecouvrez\b/g, 'Découvrez'],
  [/\bdecouvrez\b/g, 'découvrez'],
  [/\bdecouvrir\b/g, 'découvrir'],
  [/\bdecroissante\b/g, 'décroissante'],
  [/\bdeciles\b/g, 'déciles'],
  [/\bDecile\b/g, 'Décile'],
  [/\bdecile\b/g, 'décile'],
  [/\bdegradee\b/g, 'dégradée'],
  [/\bdesequilibree\b/g, 'déséquilibrée'],
  [/\bdeforme\b/g, 'déformé'],
  [/\bdevaluations\b/g, 'dévaluations'],
  [/\bdevaluation\b/g, 'dévaluation'],
  [/\bdepreciation\b/g, 'dépréciation'],
  [/\bdepreciee\b/g, 'dépréciée'],
  [/\bdepreciees\b/g, 'dépréciées'],
  [/\bdeprecies\b/g, 'dépréciés'],
  [/\bdepreciant\b/g, 'dépréciant'],
  [/\bdeprecier\b/g, 'déprécier'],
  [/\bdeflation\b/g, 'déflation'],
  [/\bDeflation\b/g, 'Déflation'],
  [/\bdeflationniste\b/g, 'déflationniste'],
  [/\bdeprimant\b/g, 'déprimant'],
  [/\brepartition\b/g, 'répartition'],
  [/\brepartit\b/g, 'répartit'],
  [/\bremuneration\b/g, 'rémunération'],
  [/\bremunere\b/g, 'rémunéré'],
  [/\bremuneree\b/g, 'rémunérée'],
  [/\breguler\b/g, 'réguler'],
  [/\bregulation\b/g, 'régulation'],
  [/\breponse\b/g, 'réponse'],
  [/\brepresentation\b/g, 'représentation'],
  [/\bRepresentation\b/g, 'Représentation'],
  [/\brepresente\b/g, 'représente'],
  [/\bresultant\b/g, 'résultant'],
  [/\bresultat\b/g, 'résultat'],
  [/\bresulte\b/g, 'résulte'],
  [/\brevele\b/g, 'révèle'],
  [/\bretablir\b/g, 'rétablir'],
  [/\bretrecit\b/g, 'rétrécit'],
  [/\breduisant\b/g, 'réduisant'],
  [/\breduirait\b/g, 'réduirait'],
  [/\breduire\b/g, 'réduire'],
  [/\breduit\b/g, 'réduit'],
  [/\breduction\b/g, 'réduction'],
  [/\bReduction\b/g, 'Réduction'],
  [/\breagit\b/g, 'réagit'],
  [/\bregressifs\b/g, 'régressifs'],
  [/\bregressif\b/g, 'régressif'],
  [/\bresiliente\b/g, 'résiliente'],
  [/\brecession\b/g, 'récession'],
  [/\bRecession\b/g, 'Récession'],
  [/\breferences\b/g, 'références'],
  [/\breference\b/g, 'référence'],
  [/\brecuperee\b/g, 'récupérée'],
  [/\breprete\b/g, 'reprêté'],
  [/\brepretee\b/g, 'reprêtée'],
  [/\brecoit\b/g, 'reçoit'],
  // e-accent at start of words
  [/\becarts\b/g, 'écarts'],
  [/\becart\b/g, 'écart'],
  [/\bEcart\b/g, 'Écart'],
  [/\bechelle\b/g, 'échelle'],
  [/\beclairage\b/g, 'éclairage'],
  [/\betirent\b/g, 'étirent'],
  [/\betroite\b/g, 'étroite'],
  [/\beloigne\b/g, 'éloigne'],
  [/\bemission\b/g, 'émission'],
  [/\bemissions\b/g, 'émissions'],
  [/\benormes\b/g, 'énormes'],
  [/\benorme\b/g, 'énorme'],
  [/\bevasion\b/g, 'évasion'],
  [/\beviction\b/g, 'éviction'],
  [/\bevolue\b/g, 'évolué'],
  // p- words
  [/\bprelevements\b/g, 'prélèvements'],
  [/\bprelevement\b/g, 'prélèvement'],
  [/\bprelevee\b/g, 'prélevée'],
  [/\bpreleve\b/g, 'prélevé'],
  [/\bprecedente\b/g, 'précédente'],
  [/\bprecedent\b/g, 'précédent'],
  [/\bprecision\b/g, 'précision'],
  [/\bprets\b/g, 'prêts'],
  // Other patterns
  [/\bprogressivite\b/g, 'progressivité'],
  [/\bProgressivite\b/g, 'Progressivité'],
  [/\bconsiderablement\b/g, 'considérablement'],
  [/\bsoutenabilite\b/g, 'soutenabilité'],
  [/\bgenerent\b/g, 'génèrent'],
  [/\bgenere\b/g, 'génère'],
  [/\bgenerer\b/g, 'générer'],
  [/\bbeneficiaires\b/g, 'bénéficiaires'],
  [/\bbeneficiaire\b/g, 'bénéficiaire'],
  [/\bbenefiques\b/g, 'bénéfiques'],
  [/\bbenefique\b/g, 'bénéfique'],
  [/\bbenefices\b/g, 'bénéfices'],
  [/\bbenefice\b/g, 'bénéfice'],
  [/\bbeneficie\b/g, 'bénéficie'],
  [/\bCarre\b/g, 'Carré'],
  [/\bcarre\b/g, 'carré'],
  [/\bCouts\b/g, 'Coûts'],
  [/\bcouts\b/g, 'coûts'],
  [/\bCout\b/g, 'Coût'],
  [/\bcout\b/g, 'coût'],
  [/\bdegage\b/g, 'dégage'],
  [/\bsuperieures\b/g, 'supérieures'],
  [/\bsuperieure\b/g, 'supérieure'],
  [/\bsuperieurs\b/g, 'supérieurs'],
  [/\bsuperieur\b/g, 'supérieur'],
  [/\binferieures\b/g, 'inférieures'],
  [/\binferieure\b/g, 'inférieure'],
  [/\binferieurs\b/g, 'inférieurs'],
  [/\binferieur\b/g, 'inférieur'],
  [/\bAvance\b/g, 'Avancé'],
  [/\bScenarios\b/g, 'Scénarios'],
  [/\bscenarios\b/g, 'scénarios'],
  [/\bScenario\b/g, 'Scénario'],
  [/\bscenario\b/g, 'scénario'],
  [/\bdonnees\b/g, 'données'],
  [/\bdonnee\b/g, 'donnée'],
  [/\bannees\b/g, 'années'],
  [/\bannee\b/g, 'année'],
  [/\bdesormais\b/g, 'désormais'],
  [/\bdeja\b/g, 'déjà'],
  [/\bbaremes\b/g, 'barèmes'],
  [/\bbareme\b/g, 'barème'],
  [/\bBareme\b/g, 'Barème'],
  [/\bacceleration\b/g, 'accélération'],
  [/\baccelere\b/g, 'accélère'],
  [/\bproblemes\b/g, 'problèmes'],
  [/\bprobleme\b/g, 'problème'],
  [/\bdernieres\b/g, 'dernières'],
  [/\bderniere\b/g, 'dernière'],
  [/\blegerement\b/g, 'légèrement'],
  [/\blegere\b/g, 'légère'],
  [/\bleger\b/g, 'léger'],
  [/\bsevere\b/g, 'sévère'],
  [/\bmatieres\b/g, 'matières'],
  [/\bmatiere\b/g, 'matière'],
  [/\bexcedentaire\b/g, 'excédentaire'],
  [/\bexcedents\b/g, 'excédents'],
  [/\bexcedent\b/g, 'excédent'],
  [/\bdouanieres\b/g, 'douanières'],
  [/\bdouaniere\b/g, 'douanière'],
  [/\bElectricite\b/g, 'Électricité'],
  [/\belectricite\b/g, 'électricité'],
  [/\bMedicament\b/g, 'Médicament'],
  [/\bmedicaments\b/g, 'médicaments'],
  [/\bmedicament\b/g, 'médicament'],
  [/\bdecennies\b/g, 'décennies'],
  [/\bdecennie\b/g, 'décennie'],
  [/\bentraine\b/g, 'entraîne'],
  [/\bentrainer\b/g, 'entraîner'],
  [/\belimine\b/g, 'élimine'],
  [/\beliminant\b/g, 'éliminant'],
  [/\bemergents\b/g, 'émergents'],
  [/\bemergent\b/g, 'émergent'],
  [/\bexige\b/g, 'exige'],  // correct
  [/\begalement\b/g, 'également'],
  [/\begale\b/g, 'égale'],
  [/\begalisant\b/g, 'égalisant'],
  [/\beliminant\b/g, 'éliminant'],
  [/\bintegre\b/g, 'intègre'],
  [/\bemprunts\b/g, 'emprunts'],  // correct
  [/\bmeme\b/g, 'même'],
  [/\bProgres\b/g, 'Progrès'],
  [/\bprogres\b/g, 'progrès'],
  [/\bdepots\b/g, 'dépôts'],
  [/\bdepot\b/g, 'dépôt'],
  [/\bDepot\b/g, 'Dépôt'],
  [/\bprete\b/g, 'prête'],
  [/\bpretent\b/g, 'prêtent'],
  [/\bcote\b/g, 'côté'],
  [/\bControle\b/g, 'Contrôle'],
  [/\bcontrole\b/g, 'contrôle'],
  [/\bcontroler\b/g, 'contrôler'],
  [/\bcontrolee\b/g, 'contrôlée'],
  [/\binteg\b/g, 'intèg'],
  [/\bdetient\b/g, 'détient'],
  [/\bdetiennent\b/g, 'détiennent'],
  [/\betat\b/g, 'état'],
  [/\bEtat\b/g, 'État'],
  [/\bdecisions\b/g, 'décisions'],
  [/\bdecision\b/g, 'décision'],
  [/\bcoincider\b/g, 'coïncider'],
  [/\bcoincide\b/g, 'coïncide'],
  [/\bforc\b/g, 'forç'],
  [/\bbrise\b/g, 'brisé'],
  [/\brevee\b/g, 'rêvée'],
  [/\breve\b/g, 'rêve'],
  [/\bimmunite\b/g, 'immunité'],
  [/\bactivite\b/g, 'activité'],
  [/\bcapacite\b/g, 'capacité'],
  [/\bcapacites\b/g, 'capacités'],
  [/\bquantite\b/g, 'quantité'],
  [/\bQuantite\b/g, 'Quantité'],
  [/\bqualite\b/g, 'qualité'],
  [/\bdurete\b/g, 'dureté'],
  [/\brarete\b/g, 'rareté'],
  [/\brarefaction\b/g, 'raréfaction'],
  [/\bsupporte\b/g, 'supporte'],  // correct - not supporté
  [/\bsupportee\b/g, 'supportée'],
  [/\butilise\b/g, 'utilise'],  // correct
  [/\butilisee\b/g, 'utilisée'],
  [/\butilisees\b/g, 'utilisées'],
  [/\butilises\b/g, 'utilisés'],
  [/\butilisent\b/g, 'utilisent'],  // correct
  [/\bdifferences\b/g, 'différences'],
  [/\bdifference\b/g, 'différence'],
  [/\bdiferent\b/g, 'différent'],
  [/\bdifferents\b/g, 'différents'],
  [/\bdifferent\b/g, 'différent'],
  [/\bdifferente\b/g, 'différente'],
  [/\bdifferentes\b/g, 'différentes'],
  [/\bbrevets\b/g, 'brevets'],  // correct
  [/\blibere\b/g, 'libéré'],
  [/\bliberees\b/g, 'libérées'],
  [/\bperseverance\b/g, 'persévérance'],
  [/\bfranc\u0327aise\b/g, 'française'],
  [/\bfrancaise\b/g, 'française'],
  [/\bfrancais\b/g, 'français'],
  [/\bs'eleve\b/g, "s'élève"],
  [/\bs'etablit\b/g, "s'établit"],
  [/\bs'ecarter\b/g, "s'écarter"],
  [/\bs'ecarte\b/g, "s'écarte"],
  [/\bs'ajusteront\b/g, "s'ajusteront"],
  [/\bs'ajustent\b/g, "s'ajustent"],
  [/\bs'effondre\b/g, "s'effondre"],
  [/\bs'eloigne\b/g, "s'éloigne"],
  [/\bd'equilibre\b/g, "d'équilibre"],
  [/\bd'egalite\b/g, "d'égalité"],
  [/\bd'economie\b/g, "d'économie"],
  [/\bd'echange\b/g, "d'échange"],
  [/\bd'echelle\b/g, "d'échelle"],
  [/\bd'eviction\b/g, "d'éviction"],
  [/\bd'interet\b/g, "d'intérêt"],
  [/\bl'economie\b/g, "l'économie"],
  [/\bl'equilibre\b/g, "l'équilibre"],
  [/\bl'echange\b/g, "l'échange"],
  [/\bl'etat\b/g, "l'état"],
  [/\bl'Etat\b/g, "l'État"],
  [/\bl'epargne\b/g, "l'épargne"],
  [/\bl'elasticite\b/g, "l'élasticité"],
  [/\bl'interet\b/g, "l'intérêt"],
  [/\bbudgetaires\b/g, 'budgétaires'],
  [/\bbudgetaire\b/g, 'budgétaire'],
  [/\bsecurite\b/g, 'sécurité'],
  [/\bSecurite\b/g, 'Sécurité'],
  // deprecie in narration context (not variable)
  [/\bdeprecier\b/g, 'déprécier'],
  [/\bdepreciee\b/g, 'dépréciée'],
  [/\bdeprecies\b/g, 'dépréciés'],
  [/\bdepreciant\b/g, 'dépréciant'],
  // parite
  [/\bparite\b/g, 'parité'],
  // aucune already correct
  // rencheri
  [/\brencheri\b/g, 'renchéri'],
  // penalise
  [/\bpenalisees\b/g, 'pénalisées'],
  [/\bpenalisee\b/g, 'pénalisée'],
  [/\bpenalises\b/g, 'pénalisés'],
  [/\bpenalise\b/g, 'pénalisé'],
  // sous-evalue
  [/\bsous-evalue\b/g, 'sous-évalué'],
  // surestim
  [/\bsurestime\b/g, 'surestime'],  // correct
  // adequation
  [/\binadequation\b/g, 'inadéquation'],
  // decourager
  [/\bdecourager\b/g, 'décourager'],
  // genereux, genereuse
  [/\bgenereux\b/g, 'généreux'],
  [/\bgenereuse\b/g, 'généreuse'],
  [/\bgenerees\b/g, 'générées'],
  [/\bgeneree\b/g, 'générée'],
  // attenuer
  [/\battenuant\b/g, 'atténuant'],
  [/\battenuer\b/g, 'atténuer'],
  // repousser
  [/\brepousse\b/g, 'repousse'],  // correct
  // redepense
  [/\bredepense\b/g, 'redépensé'],
  // l'etranger
  [/\bl'etranger\b/g, "l'étranger"],
  // libre-echange
  [/\blibre-echange\b/g, 'libre-échange'],
  // reseau
  [/\breseau\b/g, 'réseau'],
  [/\breseaux\b/g, 'réseaux'],
  // Parametres
  [/\bParametres\b/g, 'Paramètres'],
  [/\bparametres\b/g, 'paramètres'],
];

const files = getFiles('.');
let totalChanges = 0;

for (const file of files) {
  let content = readFileSync(file, 'utf-8');
  let newContent = content;

  for (const [pattern, replacement] of replacements) {
    newContent = newContent.replace(pattern, replacement);
  }

  if (newContent !== content) {
    writeFileSync(file, newContent);
    totalChanges++;
    console.log(`Fixed: ${file}`);
  }
}

console.log(`\nTotal files modified: ${totalChanges}`);
